//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 15.0.26720.2
// 
namespace UWPhospital.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DoctorData", Namespace="http://schemas.datacontract.org/2004/07/HospitalService")]
    public partial class DoctorData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string FirstNameValueField;
        
        private int IdValueField;
        
        private string LastNameValueField;
        
        private string PhoneNreValueField;
        
        private string SocNrValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstNameValue {
            get {
                return this.FirstNameValueField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameValueField, value) != true)) {
                    this.FirstNameValueField = value;
                    this.RaisePropertyChanged("FirstNameValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdValue {
            get {
                return this.IdValueField;
            }
            set {
                if ((this.IdValueField.Equals(value) != true)) {
                    this.IdValueField = value;
                    this.RaisePropertyChanged("IdValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastNameValue {
            get {
                return this.LastNameValueField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameValueField, value) != true)) {
                    this.LastNameValueField = value;
                    this.RaisePropertyChanged("LastNameValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNreValue {
            get {
                return this.PhoneNreValueField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNreValueField, value) != true)) {
                    this.PhoneNreValueField = value;
                    this.RaisePropertyChanged("PhoneNreValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SocNrValue {
            get {
                return this.SocNrValueField;
            }
            set {
                if ((object.ReferenceEquals(this.SocNrValueField, value) != true)) {
                    this.SocNrValueField = value;
                    this.RaisePropertyChanged("SocNrValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientData", Namespace="http://schemas.datacontract.org/2004/07/HospitalService")]
    public partial class PatientData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string FirstNameValueField;
        
        private int IdValueField;
        
        private string LastNameValueField;
        
        private string PhoneNreValueField;
        
        private string SocNrValueField;
        
        private string ZipCodeValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstNameValue {
            get {
                return this.FirstNameValueField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameValueField, value) != true)) {
                    this.FirstNameValueField = value;
                    this.RaisePropertyChanged("FirstNameValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdValue {
            get {
                return this.IdValueField;
            }
            set {
                if ((this.IdValueField.Equals(value) != true)) {
                    this.IdValueField = value;
                    this.RaisePropertyChanged("IdValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastNameValue {
            get {
                return this.LastNameValueField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameValueField, value) != true)) {
                    this.LastNameValueField = value;
                    this.RaisePropertyChanged("LastNameValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNreValue {
            get {
                return this.PhoneNreValueField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNreValueField, value) != true)) {
                    this.PhoneNreValueField = value;
                    this.RaisePropertyChanged("PhoneNreValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SocNrValue {
            get {
                return this.SocNrValueField;
            }
            set {
                if ((object.ReferenceEquals(this.SocNrValueField, value) != true)) {
                    this.SocNrValueField = value;
                    this.RaisePropertyChanged("SocNrValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCodeValue {
            get {
                return this.ZipCodeValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeValueField, value) != true)) {
                    this.ZipCodeValueField = value;
                    this.RaisePropertyChanged("ZipCodeValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JournalData", Namespace="http://schemas.datacontract.org/2004/07/HospitalService")]
    public partial class JournalData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime DateTimeValueField;
        
        private int DoctorIdValueField;
        
        private int IdValueField;
        
        private int PatientIdValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTimeValue {
            get {
                return this.DateTimeValueField;
            }
            set {
                if ((this.DateTimeValueField.Equals(value) != true)) {
                    this.DateTimeValueField = value;
                    this.RaisePropertyChanged("DateTimeValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DoctorIdValue {
            get {
                return this.DoctorIdValueField;
            }
            set {
                if ((this.DoctorIdValueField.Equals(value) != true)) {
                    this.DoctorIdValueField = value;
                    this.RaisePropertyChanged("DoctorIdValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdValue {
            get {
                return this.IdValueField;
            }
            set {
                if ((this.IdValueField.Equals(value) != true)) {
                    this.IdValueField = value;
                    this.RaisePropertyChanged("IdValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PatientIdValue {
            get {
                return this.PatientIdValueField;
            }
            set {
                if ((this.PatientIdValueField.Equals(value) != true)) {
                    this.PatientIdValueField = value;
                    this.RaisePropertyChanged("PatientIdValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HospitalPostlData", Namespace="http://schemas.datacontract.org/2004/07/HospitalService")]
    public partial class HospitalPostlData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<System.DateTime> DateTimeValueField;
        
        private System.Nullable<int> DoctorIdValueField;
        
        private int IdValueField;
        
        private System.Nullable<int> JournalIdValueField;
        
        private string PostValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateTimeValue {
            get {
                return this.DateTimeValueField;
            }
            set {
                if ((this.DateTimeValueField.Equals(value) != true)) {
                    this.DateTimeValueField = value;
                    this.RaisePropertyChanged("DateTimeValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DoctorIdValue {
            get {
                return this.DoctorIdValueField;
            }
            set {
                if ((this.DoctorIdValueField.Equals(value) != true)) {
                    this.DoctorIdValueField = value;
                    this.RaisePropertyChanged("DoctorIdValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdValue {
            get {
                return this.IdValueField;
            }
            set {
                if ((this.IdValueField.Equals(value) != true)) {
                    this.IdValueField = value;
                    this.RaisePropertyChanged("IdValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> JournalIdValue {
            get {
                return this.JournalIdValueField;
            }
            set {
                if ((this.JournalIdValueField.Equals(value) != true)) {
                    this.JournalIdValueField = value;
                    this.RaisePropertyChanged("JournalIdValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostValue {
            get {
                return this.PostValueField;
            }
            set {
                if ((object.ReferenceEquals(this.PostValueField, value) != true)) {
                    this.PostValueField = value;
                    this.RaisePropertyChanged("PostValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DoctorXPatientData", Namespace="http://schemas.datacontract.org/2004/07/HospitalService")]
    public partial class DoctorXPatientData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int DoctorIdValueField;
        
        private string HospitalValueField;
        
        private int IdValueField;
        
        private int PatientIdValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DoctorIdValue {
            get {
                return this.DoctorIdValueField;
            }
            set {
                if ((this.DoctorIdValueField.Equals(value) != true)) {
                    this.DoctorIdValueField = value;
                    this.RaisePropertyChanged("DoctorIdValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HospitalValue {
            get {
                return this.HospitalValueField;
            }
            set {
                if ((object.ReferenceEquals(this.HospitalValueField, value) != true)) {
                    this.HospitalValueField = value;
                    this.RaisePropertyChanged("HospitalValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdValue {
            get {
                return this.IdValueField;
            }
            set {
                if ((this.IdValueField.Equals(value) != true)) {
                    this.IdValueField = value;
                    this.RaisePropertyChanged("IdValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PatientIdValue {
            get {
                return this.PatientIdValueField;
            }
            set {
                if ((this.PatientIdValueField.Equals(value) != true)) {
                    this.PatientIdValueField = value;
                    this.RaisePropertyChanged("PatientIdValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HospitalPostlDataWithPatientName", Namespace="http://schemas.datacontract.org/2004/07/HospitalService")]
    public partial class HospitalPostlDataWithPatientName : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<System.DateTime> DateTimeValueField;
        
        private System.Nullable<int> DoctorIdValueField;
        
        private int IdValueField;
        
        private System.Nullable<int> JournalIdValueField;
        
        private string PostValueField;
        
        private string patientFirstNameValueField;
        
        private string patientLastNameValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateTimeValue {
            get {
                return this.DateTimeValueField;
            }
            set {
                if ((this.DateTimeValueField.Equals(value) != true)) {
                    this.DateTimeValueField = value;
                    this.RaisePropertyChanged("DateTimeValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DoctorIdValue {
            get {
                return this.DoctorIdValueField;
            }
            set {
                if ((this.DoctorIdValueField.Equals(value) != true)) {
                    this.DoctorIdValueField = value;
                    this.RaisePropertyChanged("DoctorIdValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdValue {
            get {
                return this.IdValueField;
            }
            set {
                if ((this.IdValueField.Equals(value) != true)) {
                    this.IdValueField = value;
                    this.RaisePropertyChanged("IdValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> JournalIdValue {
            get {
                return this.JournalIdValueField;
            }
            set {
                if ((this.JournalIdValueField.Equals(value) != true)) {
                    this.JournalIdValueField = value;
                    this.RaisePropertyChanged("JournalIdValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostValue {
            get {
                return this.PostValueField;
            }
            set {
                if ((object.ReferenceEquals(this.PostValueField, value) != true)) {
                    this.PostValueField = value;
                    this.RaisePropertyChanged("PostValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string patientFirstNameValue {
            get {
                return this.patientFirstNameValueField;
            }
            set {
                if ((object.ReferenceEquals(this.patientFirstNameValueField, value) != true)) {
                    this.patientFirstNameValueField = value;
                    this.RaisePropertyChanged("patientFirstNameValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string patientLastNameValue {
            get {
                return this.patientLastNameValueField;
            }
            set {
                if ((object.ReferenceEquals(this.patientLastNameValueField, value) != true)) {
                    this.patientLastNameValueField = value;
                    this.RaisePropertyChanged("patientLastNameValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDoctors", ReplyAction="http://tempuri.org/IService1/GetDoctorsResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<UWPhospital.ServiceReference1.DoctorData>> GetDoctorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSpecificDoctor", ReplyAction="http://tempuri.org/IService1/GetSpecificDoctorResponse")]
        System.Threading.Tasks.Task<UWPhospital.ServiceReference1.DoctorData> GetSpecificDoctorAsync(System.Nullable<int> doctorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPatients", ReplyAction="http://tempuri.org/IService1/GetPatientsResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<UWPhospital.ServiceReference1.PatientData>> GetPatientsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetJournals", ReplyAction="http://tempuri.org/IService1/GetJournalsResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<UWPhospital.ServiceReference1.JournalData>> GetJournalsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHospitalPosts", ReplyAction="http://tempuri.org/IService1/GetHospitalPostsResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<UWPhospital.ServiceReference1.HospitalPostlData>> GetHospitalPostsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDoctorXPatients", ReplyAction="http://tempuri.org/IService1/GetDoctorXPatientsResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<UWPhospital.ServiceReference1.DoctorXPatientData>> GetDoctorXPatientsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckLogIn", ReplyAction="http://tempuri.org/IService1/CheckLogInResponse")]
        System.Threading.Tasks.Task<UWPhospital.ServiceReference1.DoctorData> CheckLogInAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ImportNewDoctor", ReplyAction="http://tempuri.org/IService1/ImportNewDoctorResponse")]
        System.Threading.Tasks.Task<bool> ImportNewDoctorAsync(string firstname, string lastname, string soc, string phonenumber, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ImportNewPatient", ReplyAction="http://tempuri.org/IService1/ImportNewPatientResponse")]
        System.Threading.Tasks.Task<bool> ImportNewPatientAsync(int journalId, string soc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateNewPatient", ReplyAction="http://tempuri.org/IService1/CreateNewPatientResponse")]
        System.Threading.Tasks.Task<bool> CreateNewPatientAsync(string userEmail, string password, string firstname, string lastname, string soc, string phonenr, string zipcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateDoctorInformation", ReplyAction="http://tempuri.org/IService1/UpdateDoctorInformationResponse")]
        System.Threading.Tasks.Task<string> UpdateDoctorInformationAsync(int doctorId, string newEmail, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateHospitalPost", ReplyAction="http://tempuri.org/IService1/CreateHospitalPostResponse")]
        System.Threading.Tasks.Task<bool> CreateHospitalPostAsync(int doctorId, int patientId, string post);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHospitalPostForPatient", ReplyAction="http://tempuri.org/IService1/GetHospitalPostForPatientResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<UWPhospital.ServiceReference1.HospitalPostlData>> GetHospitalPostForPatientAsync(int patientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetThreeLastHospitalPosts", ReplyAction="http://tempuri.org/IService1/GetThreeLastHospitalPostsResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<UWPhospital.ServiceReference1.HospitalPostlDataWithPatientName>> GetThreeLastHospitalPostsAsync(int doctorId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : UWPhospital.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<UWPhospital.ServiceReference1.IService1>, UWPhospital.ServiceReference1.IService1 {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<UWPhospital.ServiceReference1.DoctorData>> GetDoctorsAsync() {
            return base.Channel.GetDoctorsAsync();
        }
        
        public System.Threading.Tasks.Task<UWPhospital.ServiceReference1.DoctorData> GetSpecificDoctorAsync(System.Nullable<int> doctorId) {
            return base.Channel.GetSpecificDoctorAsync(doctorId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<UWPhospital.ServiceReference1.PatientData>> GetPatientsAsync() {
            return base.Channel.GetPatientsAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<UWPhospital.ServiceReference1.JournalData>> GetJournalsAsync() {
            return base.Channel.GetJournalsAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<UWPhospital.ServiceReference1.HospitalPostlData>> GetHospitalPostsAsync() {
            return base.Channel.GetHospitalPostsAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<UWPhospital.ServiceReference1.DoctorXPatientData>> GetDoctorXPatientsAsync() {
            return base.Channel.GetDoctorXPatientsAsync();
        }
        
        public System.Threading.Tasks.Task<UWPhospital.ServiceReference1.DoctorData> CheckLogInAsync(string username, string password) {
            return base.Channel.CheckLogInAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> ImportNewDoctorAsync(string firstname, string lastname, string soc, string phonenumber, string username, string password) {
            return base.Channel.ImportNewDoctorAsync(firstname, lastname, soc, phonenumber, username, password);
        }
        
        public System.Threading.Tasks.Task<bool> ImportNewPatientAsync(int journalId, string soc) {
            return base.Channel.ImportNewPatientAsync(journalId, soc);
        }
        
        public System.Threading.Tasks.Task<bool> CreateNewPatientAsync(string userEmail, string password, string firstname, string lastname, string soc, string phonenr, string zipcode) {
            return base.Channel.CreateNewPatientAsync(userEmail, password, firstname, lastname, soc, phonenr, zipcode);
        }
        
        public System.Threading.Tasks.Task<string> UpdateDoctorInformationAsync(int doctorId, string newEmail, string newPassword) {
            return base.Channel.UpdateDoctorInformationAsync(doctorId, newEmail, newPassword);
        }
        
        public System.Threading.Tasks.Task<bool> CreateHospitalPostAsync(int doctorId, int patientId, string post) {
            return base.Channel.CreateHospitalPostAsync(doctorId, patientId, post);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<UWPhospital.ServiceReference1.HospitalPostlData>> GetHospitalPostForPatientAsync(int patientId) {
            return base.Channel.GetHospitalPostForPatientAsync(patientId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<UWPhospital.ServiceReference1.HospitalPostlDataWithPatientName>> GetThreeLastHospitalPostsAsync(int doctorId) {
            return base.Channel.GetThreeLastHospitalPostsAsync(doctorId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:50995/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IService1,
        }
    }
}
