//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalPost
    {
        public int Id { get; set; }
        public Nullable<int> Doctor_id { get; set; }
        public Nullable<int> Journal_id { get; set; }
        public string Post { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Journal Journal { get; set; }
    }
}
